name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Backend Docker Image
      run: docker build -t my-backend ./Backend

    - name: Build Frontend Docker Image
      run: docker build -t my-frontend ./Frontend

    - name: Run Docker Compose (Test)
      run: docker-compose up -d

    - name: Run Tests
      run: |
        docker exec backend-service npm run test

    - name: Push Docker Images to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag my-backend username/my-backend:latest
        docker tag my-frontend username/my-frontend:latest
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push username/my-backend:latest
        docker push username/my-frontend:latest

    - name: Clean Up
      run: docker-compose down
