name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Backend Docker Image
      run: docker build -t my-backend ./Backend

    - name: Build Frontend Docker Image
      run: docker build -t my-frontend ./Frontend

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Run Docker Compose (Test)
      run: docker-compose up -d

    # Log in to Docker Hub using GitHub secrets
    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Images to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag my-backend username/my-backend:latest
        docker tag my-frontend username/my-frontend:latest
        docker push username/my-backend:latest
        docker push username/my-frontend:latest

    - name: Clean Up
      run: docker-compose down
